import { HSKLevel, Word, GrammarTopic } from './types';

export const INITIAL_WORDS: Word[] = [
  // --- HSK 1 (150 Words) ---
  { id: '1-1', char: '爱', pinyin: 'ài', en: 'to love', level: HSKLevel.HSK1 },
  { id: '1-2', char: '八', pinyin: 'bā', en: 'eight', level: HSKLevel.HSK1 },
  { id: '1-3', char: '爸爸', pinyin: 'bàba', en: 'father', level: HSKLevel.HSK1 },
  { id: '1-4', char: '杯子', pinyin: 'bēizi', en: 'cup; glass', level: HSKLevel.HSK1 },
  { id: '1-5', char: '北京', pinyin: 'Běijīng', en: 'Beijing', level: HSKLevel.HSK1 },
  { id: '1-6', char: '本', pinyin: 'běn', en: 'measure word for books', level: HSKLevel.HSK1 },
  { id: '1-7', char: '不客气', pinyin: 'búkèqi', en: 'you are welcome', level: HSKLevel.HSK1 },
  { id: '1-8', char: '不', pinyin: 'bù', en: 'not; no', level: HSKLevel.HSK1 },
  { id: '1-9', char: '菜', pinyin: 'cài', en: 'dish; vegetable', level: HSKLevel.HSK1 },
  { id: '1-10', char: '茶', pinyin: 'chá', en: 'tea', level: HSKLevel.HSK1 },
  { id: '1-11', char: '吃', pinyin: 'chī', en: 'to eat', level: HSKLevel.HSK1 },
  { id: '1-12', char: '出租车', pinyin: 'chūzūchē', en: 'taxi', level: HSKLevel.HSK1 },
  { id: '1-13', char: '打电话', pinyin: 'dǎ diànhuà', en: 'to make a phone call', level: HSKLevel.HSK1 },
  { id: '1-14', char: '大', pinyin: 'dà', en: 'big', level: HSKLevel.HSK1 },
  { id: '1-15', char: '的', pinyin: 'de', en: 'possessive particle', level: HSKLevel.HSK1 },
  { id: '1-16', char: '点', pinyin: 'diǎn', en: 'o\'clock', level: HSKLevel.HSK1 },
  { id: '1-17', char: '电脑', pinyin: 'diànnǎo', en: 'computer', level: HSKLevel.HSK1 },
  { id: '1-18', char: '电视', pinyin: 'diànshì', en: 'television', level: HSKLevel.HSK1 },
  { id: '1-19', char: '电影', pinyin: 'diànyǐng', en: 'movie', level: HSKLevel.HSK1 },
  { id: '1-20', char: '东西', pinyin: 'dōngxi', en: 'thing; stuff', level: HSKLevel.HSK1 },
  { id: '1-21', char: '都', pinyin: 'dōu', en: 'all; both', level: HSKLevel.HSK1 },
  { id: '1-22', char: '读', pinyin: 'dú', en: 'to read', level: HSKLevel.HSK1 },
  { id: '1-23', char: '对不起', pinyin: 'duìbuqǐ', en: 'sorry', level: HSKLevel.HSK1 },
  { id: '1-24', char: '多', pinyin: 'duō', en: 'many; much', level: HSKLevel.HSK1 },
  { id: '1-25', char: '多少', pinyin: 'duōshao', en: 'how many; how much', level: HSKLevel.HSK1 },
  { id: '1-26', char: '儿子', pinyin: 'érzi', en: 'son', level: HSKLevel.HSK1 },
  { id: '1-27', char: '二', pinyin: 'èr', en: 'two', level: HSKLevel.HSK1 },
  { id: '1-28', char: '饭店', pinyin: 'fàndiàn', en: 'restaurant', level: HSKLevel.HSK1 },
  { id: '1-29', char: '飞机', pinyin: 'fēijī', en: 'airplane', level: HSKLevel.HSK1 },
  { id: '1-30', char: '分钟', pinyin: 'fēnzhōng', en: 'minute', level: HSKLevel.HSK1 },
  { id: '1-31', char: '高兴', pinyin: 'gāoxìng', en: 'happy', level: HSKLevel.HSK1 },
  { id: '1-32', char: '个', pinyin: 'gè', en: 'general measure word', level: HSKLevel.HSK1 },
  { id: '1-33', char: '工作', pinyin: 'gōngzuò', en: 'job; to work', level: HSKLevel.HSK1 },
  { id: '1-34', char: '狗', pinyin: 'gǒu', en: 'dog', level: HSKLevel.HSK1 },
  { id: '1-35', char: '汉语', pinyin: 'Hànyǔ', en: 'Chinese language', level: HSKLevel.HSK1 },
  { id: '1-36', char: '好', pinyin: 'hǎo', en: 'good', level: HSKLevel.HSK1 },
  { id: '1-37', char: '号', pinyin: 'hào', en: 'day of month; number', level: HSKLevel.HSK1 },
  { id: '1-38', char: '喝', pinyin: 'hē', en: 'to drink', level: HSKLevel.HSK1 },
  { id: '1-39', char: '和', pinyin: 'hé', en: 'and', level: HSKLevel.HSK1 },
  { id: '1-40', char: '很', pinyin: 'hěn', en: 'very', level: HSKLevel.HSK1 },
  { id: '1-41', char: '后面', pinyin: 'hòumian', en: 'behind', level: HSKLevel.HSK1 },
  { id: '1-42', char: '回', pinyin: 'huí', en: 'to return', level: HSKLevel.HSK1 },
  { id: '1-43', char: '会', pinyin: 'huì', en: 'can; to be able to', level: HSKLevel.HSK1 },
  { id: '1-44', char: '几', pinyin: 'jǐ', en: 'how many', level: HSKLevel.HSK1 },
  { id: '1-45', char: '家', pinyin: 'jiā', en: 'family; home', level: HSKLevel.HSK1 },
  { id: '1-46', char: '叫', pinyin: 'jiào', en: 'to be called', level: HSKLevel.HSK1 },
  { id: '1-47', char: '今天', pinyin: 'jīntiān', en: 'today', level: HSKLevel.HSK1 },
  { id: '1-48', char: '九', pinyin: 'jiǔ', en: 'nine', level: HSKLevel.HSK1 },
  { id: '1-49', char: '开', pinyin: 'kāi', en: 'to open; to drive', level: HSKLevel.HSK1 },
  { id: '1-50', char: '看', pinyin: 'kàn', en: 'to look; to watch', level: HSKLevel.HSK1 },
  { id: '1-51', char: '看见', pinyin: 'kànjiàn', en: 'to see', level: HSKLevel.HSK1 },
  { id: '1-52', char: '块', pinyin: 'kuài', en: 'piece; yuan', level: HSKLevel.HSK1 },
  { id: '1-53', char: '来', pinyin: 'lái', en: 'to come', level: HSKLevel.HSK1 },
  { id: '1-54', char: '老师', pinyin: 'lǎoshī', en: 'teacher', level: HSKLevel.HSK1 },
  { id: '1-55', char: '了', pinyin: 'le', en: 'particle indicating change', level: HSKLevel.HSK1 },
  { id: '1-56', char: '冷', pinyin: 'lěng', en: 'cold', level: HSKLevel.HSK1 },
  { id: '1-57', char: '里', pinyin: 'lǐ', en: 'inside', level: HSKLevel.HSK1 },
  { id: '1-58', char: '零', pinyin: 'líng', en: 'zero', level: HSKLevel.HSK1 },
  { id: '1-59', char: '六', pinyin: 'liù', en: 'six', level: HSKLevel.HSK1 },
  { id: '1-60', char: '妈妈', pinyin: 'māma', en: 'mother', level: HSKLevel.HSK1 },
  { id: '1-61', char: '吗', pinyin: 'ma', en: 'question particle', level: HSKLevel.HSK1 },
  { id: '1-62', char: '买', pinyin: 'mǎi', en: 'to buy', level: HSKLevel.HSK1 },
  { id: '1-63', char: '猫', pinyin: 'māo', en: 'cat', level: HSKLevel.HSK1 },
  { id: '1-64', char: '没', pinyin: 'méi', en: 'not', level: HSKLevel.HSK1 },
  { id: '1-65', char: '没关系', pinyin: 'méiguānxi', en: 'it doesn\'t matter', level: HSKLevel.HSK1 },
  { id: '1-66', char: '米饭', pinyin: 'mǐfàn', en: 'cooked rice', level: HSKLevel.HSK1 },
  { id: '1-67', char: '明天', pinyin: 'míngtiān', en: 'tomorrow', level: HSKLevel.HSK1 },
  { id: '1-68', char: '名字', pinyin: 'míngzi', en: 'name', level: HSKLevel.HSK1 },
  { id: '1-69', char: '哪', pinyin: 'nǎ', en: 'which', level: HSKLevel.HSK1 },
  { id: '1-70', char: '哪儿', pinyin: 'nǎr', en: 'where', level: HSKLevel.HSK1 },
  { id: '1-71', char: '那', pinyin: 'nà', en: 'that', level: HSKLevel.HSK1 },
  { id: '1-72', char: '那儿', pinyin: 'nàr', en: 'there', level: HSKLevel.HSK1 },
  { id: '1-73', char: '呢', pinyin: 'ne', en: 'particle indicating question', level: HSKLevel.HSK1 },
  { id: '1-74', char: '能', pinyin: 'néng', en: 'can; be able to', level: HSKLevel.HSK1 },
  { id: '1-75', char: '你', pinyin: 'nǐ', en: 'you', level: HSKLevel.HSK1 },
  { id: '1-76', char: '年', pinyin: 'nián', en: 'year', level: HSKLevel.HSK1 },
  { id: '1-77', char: '女儿', pinyin: 'nǚ\'ér', en: 'daughter', level: HSKLevel.HSK1 },
  { id: '1-78', char: '朋友', pinyin: 'péngyou', en: 'friend', level: HSKLevel.HSK1 },
  { id: '1-79', char: '漂亮', pinyin: 'piàoliang', en: 'beautiful', level: HSKLevel.HSK1 },
  { id: '1-80', char: '苹果', pinyin: 'píngguǒ', en: 'apple', level: HSKLevel.HSK1 },
  { id: '1-81', char: '七', pinyin: 'qī', en: 'seven', level: HSKLevel.HSK1 },
  { id: '1-82', char: '钱', pinyin: 'qián', en: 'money', level: HSKLevel.HSK1 },
  { id: '1-83', char: '前面', pinyin: 'qiánmian', en: 'front', level: HSKLevel.HSK1 },
  { id: '1-84', char: '请', pinyin: 'qǐng', en: 'please', level: HSKLevel.HSK1 },
  { id: '1-85', char: '去', pinyin: 'qù', en: 'to go', level: HSKLevel.HSK1 },
  { id: '1-86', char: '热', pinyin: 'rè', en: 'hot', level: HSKLevel.HSK1 },
  { id: '1-87', char: '人', pinyin: 'rén', en: 'person', level: HSKLevel.HSK1 },
  { id: '1-88', char: '认识', pinyin: 'rènshi', en: 'to know (someone)', level: HSKLevel.HSK1 },
  { id: '1-89', char: '三', pinyin: 'sān', en: 'three', level: HSKLevel.HSK1 },
  { id: '1-90', char: '商店', pinyin: 'shāngdiàn', en: 'shop', level: HSKLevel.HSK1 },
  { id: '1-91', char: '上', pinyin: 'shàng', en: 'up; above', level: HSKLevel.HSK1 },
  { id: '1-92', char: '上午', pinyin: 'shàngwǔ', en: 'morning', level: HSKLevel.HSK1 },
  { id: '1-93', char: '少', pinyin: 'shǎo', en: 'few; little', level: HSKLevel.HSK1 },
  { id: '1-94', char: '谁', pinyin: 'shéi', en: 'who', level: HSKLevel.HSK1 },
  { id: '1-95', char: '什么', pinyin: 'shénme', en: 'what', level: HSKLevel.HSK1 },
  { id: '1-96', char: '十', pinyin: 'shí', en: 'ten', level: HSKLevel.HSK1 },
  { id: '1-97', char: '时候', pinyin: 'shíhou', en: 'time; moment', level: HSKLevel.HSK1 },
  { id: '1-98', char: '是', pinyin: 'shì', en: 'to be', level: HSKLevel.HSK1 },
  { id: '1-99', char: '书', pinyin: 'shū', en: 'book', level: HSKLevel.HSK1 },
  { id: '1-100', char: '水', pinyin: 'shuǐ', en: 'water', level: HSKLevel.HSK1 },
  { id: '1-101', char: '水果', pinyin: 'shuǐguǒ', en: 'fruit', level: HSKLevel.HSK1 },
  { id: '1-102', char: '睡觉', pinyin: 'shuìjiào', en: 'to sleep', level: HSKLevel.HSK1 },
  { id: '1-103', char: '说', pinyin: 'shuō', en: 'to speak', level: HSKLevel.HSK1 },
  { id: '1-104', char: '四', pinyin: 'sì', en: 'four', level: HSKLevel.HSK1 },
  { id: '1-105', char: '岁', pinyin: 'suì', en: 'years old', level: HSKLevel.HSK1 },
  { id: '1-106', char: '他', pinyin: 'tā', en: 'he', level: HSKLevel.HSK1 },
  { id: '1-107', char: '她', pinyin: 'tā', en: 'she', level: HSKLevel.HSK1 },
  { id: '1-108', char: '太', pinyin: 'tài', en: 'too; extremely', level: HSKLevel.HSK1 },
  { id: '1-109', char: '天气', pinyin: 'tiānqì', en: 'weather', level: HSKLevel.HSK1 },
  { id: '1-110', char: '听', pinyin: 'tīng', en: 'to listen', level: HSKLevel.HSK1 },
  { id: '1-111', char: '同学', pinyin: 'tóngxué', en: 'classmate', level: HSKLevel.HSK1 },
  { id: '1-112', char: '喂', pinyin: 'wèi', en: 'hello (on phone)', level: HSKLevel.HSK1 },
  { id: '1-113', char: '我', pinyin: 'wǒ', en: 'I; me', level: HSKLevel.HSK1 },
  { id: '1-114', char: '我们', pinyin: 'wǒmen', en: 'we; us', level: HSKLevel.HSK1 },
  { id: '1-115', char: '五', pinyin: 'wǔ', en: 'five', level: HSKLevel.HSK1 },
  { id: '1-116', char: '喜欢', pinyin: 'xǐhuan', en: 'to like', level: HSKLevel.HSK1 },
  { id: '1-117', char: '下', pinyin: 'xià', en: 'down; below', level: HSKLevel.HSK1 },
  { id: '1-118', char: '下午', pinyin: 'xiàwǔ', en: 'afternoon', level: HSKLevel.HSK1 },
  { id: '1-119', char: '下雨', pinyin: 'xiàyǔ', en: 'to rain', level: HSKLevel.HSK1 },
  { id: '1-120', char: '先生', pinyin: 'xiānsheng', en: 'Mr.; husband', level: HSKLevel.HSK1 },
  { id: '1-121', char: '现在', pinyin: 'xiànzài', en: 'now', level: HSKLevel.HSK1 },
  { id: '1-122', char: '想', pinyin: 'xiǎng', en: 'to want; to think', level: HSKLevel.HSK1 },
  { id: '1-123', char: '小', pinyin: 'xiǎo', en: 'small', level: HSKLevel.HSK1 },
  { id: '1-124', char: '小姐', pinyin: 'xiǎojiě', en: 'Miss', level: HSKLevel.HSK1 },
  { id: '1-125', char: '些', pinyin: 'xiē', en: 'some', level: HSKLevel.HSK1 },
  { id: '1-126', char: '写', pinyin: 'xiě', en: 'to write', level: HSKLevel.HSK1 },
  { id: '1-127', char: '谢谢', pinyin: 'xièxie', en: 'thanks', level: HSKLevel.HSK1 },
  { id: '1-128', char: '星期', pinyin: 'xīngqī', en: 'week', level: HSKLevel.HSK1 },
  { id: '1-129', char: '学生', pinyin: 'xuésheng', en: 'student', level: HSKLevel.HSK1 },
  { id: '1-130', char: '学习', pinyin: 'xuéxí', en: 'to study', level: HSKLevel.HSK1 },
  { id: '1-131', char: '学校', pinyin: 'xuéxiào', en: 'school', level: HSKLevel.HSK1 },
  { id: '1-132', char: '一', pinyin: 'yī', en: 'one', level: HSKLevel.HSK1 },
  { id: '1-133', char: '衣服', pinyin: 'yīfu', en: 'clothes', level: HSKLevel.HSK1 },
  { id: '1-134', char: '医生', pinyin: 'yīshēng', en: 'doctor', level: HSKLevel.HSK1 },
  { id: '1-135', char: '医院', pinyin: 'yīyuàn', en: 'hospital', level: HSKLevel.HSK1 },
  { id: '1-136', char: '椅子', pinyin: 'yǐzi', en: 'chair', level: HSKLevel.HSK1 },
  { id: '1-137', char: '有', pinyin: 'yǒu', en: 'to have', level: HSKLevel.HSK1 },
  { id: '1-138', char: '月', pinyin: 'yuè', en: 'month', level: HSKLevel.HSK1 },
  { id: '1-139', char: '再见', pinyin: 'zàijiàn', en: 'goodbye', level: HSKLevel.HSK1 },
  { id: '1-140', char: '在', pinyin: 'zài', en: 'at; in', level: HSKLevel.HSK1 },
  { id: '1-141', char: '怎么', pinyin: 'zěnme', en: 'how', level: HSKLevel.HSK1 },
  { id: '1-142', char: '怎么样', pinyin: 'zěnmeyàng', en: 'how about', level: HSKLevel.HSK1 },
  { id: '1-143', char: '这', pinyin: 'zhè', en: 'this', level: HSKLevel.HSK1 },
  { id: '1-144', char: '这儿', pinyin: 'zhèr', en: 'here', level: HSKLevel.HSK1 },
  { id: '1-145', char: '中国', pinyin: 'Zhōngguó', en: 'China', level: HSKLevel.HSK1 },
  { id: '1-146', char: '中午', pinyin: 'zhōngwǔ', en: 'noon', level: HSKLevel.HSK1 },
  { id: '1-147', char: '住', pinyin: 'zhù', en: 'to live', level: HSKLevel.HSK1 },
  { id: '1-148', char: '桌子', pinyin: 'zhuōzi', en: 'table', level: HSKLevel.HSK1 },
  { id: '1-149', char: '字', pinyin: 'zì', en: 'character', level: HSKLevel.HSK1 },
  { id: '1-150', char: '昨天', pinyin: 'zuótiān', en: 'yesterday', level: HSKLevel.HSK1 },

  // --- HSK 2 (150 Words) ---
  { id: '2-1', char: '吧', pinyin: 'ba', en: 'suggestion particle', level: HSKLevel.HSK2 },
  { id: '2-2', char: '白', pinyin: 'bái', en: 'white', level: HSKLevel.HSK2 },
  { id: '2-3', char: '百', pinyin: 'bǎi', en: 'hundred', level: HSKLevel.HSK2 },
  { id: '2-4', char: '帮助', pinyin: 'bāngzhù', en: 'to help', level: HSKLevel.HSK2 },
  { id: '2-5', char: '报纸', pinyin: 'bàozhǐ', en: 'newspaper', level: HSKLevel.HSK2 },
  { id: '2-6', char: '比', pinyin: 'bǐ', en: 'to compare', level: HSKLevel.HSK2 },
  { id: '2-7', char: '别', pinyin: 'bié', en: 'do not', level: HSKLevel.HSK2 },
  { id: '2-8', char: '长', pinyin: 'cháng', en: 'long', level: HSKLevel.HSK2 },
  { id: '2-9', char: '唱歌', pinyin: 'chànggē', en: 'to sing', level: HSKLevel.HSK2 },
  { id: '2-10', char: '出', pinyin: 'chū', en: 'to go out', level: HSKLevel.HSK2 },
  { id: '2-11', char: '穿', pinyin: 'chuān', en: 'to wear', level: HSKLevel.HSK2 },
  { id: '2-12', char: '次', pinyin: 'cì', en: 'number of times', level: HSKLevel.HSK2 },
  { id: '2-13', char: '从', pinyin: 'cóng', en: 'from', level: HSKLevel.HSK2 },
  { id: '2-14', char: '错', pinyin: 'cuò', en: 'wrong', level: HSKLevel.HSK2 },
  { id: '2-15', char: '打篮球', pinyin: 'dǎ lánqiú', en: 'play basketball', level: HSKLevel.HSK2 },
  { id: '2-16', char: '大家', pinyin: 'dàjiā', en: 'everyone', level: HSKLevel.HSK2 },
  { id: '2-17', char: '到', pinyin: 'dào', en: 'to arrive', level: HSKLevel.HSK2 },
  { id: '2-18', char: '得', pinyin: 'de', en: 'particle for complement', level: HSKLevel.HSK2 },
  { id: '2-19', char: '等等', pinyin: 'děngděng', en: 'etc.', level: HSKLevel.HSK2 },
  { id: '2-20', char: '弟弟', pinyin: 'dìdi', en: 'younger brother', level: HSKLevel.HSK2 },
  { id: '2-21', char: '第一', pinyin: 'dìyī', en: 'first', level: HSKLevel.HSK2 },
  { id: '2-22', char: '懂', pinyin: 'dǒng', en: 'to understand', level: HSKLevel.HSK2 },
  { id: '2-23', char: '对', pinyin: 'duì', en: 'correct; right', level: HSKLevel.HSK2 },
  { id: '2-24', char: '房间', pinyin: 'fángjiān', en: 'room', level: HSKLevel.HSK2 },
  { id: '2-25', char: '非常', pinyin: 'fēicháng', en: 'very; extremely', level: HSKLevel.HSK2 },
  { id: '2-26', char: '服务员', pinyin: 'fúwùyuán', en: 'waiter', level: HSKLevel.HSK2 },
  { id: '2-27', char: '高', pinyin: 'gāo', en: 'tall; high', level: HSKLevel.HSK2 },
  { id: '2-28', char: '告诉', pinyin: 'gàosu', en: 'to tell', level: HSKLevel.HSK2 },
  { id: '2-29', char: '哥哥', pinyin: 'gēge', en: 'older brother', level: HSKLevel.HSK2 },
  { id: '2-30', char: '给', pinyin: 'gěi', en: 'to give', level: HSKLevel.HSK2 },
  { id: '2-31', char: '公共汽车', pinyin: 'gōnggòngqìchē', en: 'bus', level: HSKLevel.HSK2 },
  { id: '2-32', char: '公司', pinyin: 'gōngsī', en: 'company', level: HSKLevel.HSK2 },
  { id: '2-33', char: '贵', pinyin: 'guì', en: 'expensive', level: HSKLevel.HSK2 },
  { id: '2-34', char: '过', pinyin: 'guo', en: 'aspect particle', level: HSKLevel.HSK2 },
  { id: '2-35', char: '还', pinyin: 'hái', en: 'still; yet', level: HSKLevel.HSK2 },
  { id: '2-36', char: '孩子', pinyin: 'háizi', en: 'child', level: HSKLevel.HSK2 },
  { id: '2-37', char: '好吃', pinyin: 'hǎochī', en: 'delicious', level: HSKLevel.HSK2 },
  { id: '2-38', char: '黑', pinyin: 'hēi', en: 'black', level: HSKLevel.HSK2 },
  { id: '2-39', char: '红', pinyin: 'hóng', en: 'red', level: HSKLevel.HSK2 },
  { id: '2-40', char: '火车站', pinyin: 'huǒchēzhàn', en: 'train station', level: HSKLevel.HSK2 },
  { id: '2-41', char: '机场', pinyin: 'jīchǎng', en: 'airport', level: HSKLevel.HSK2 },
  { id: '2-42', char: '鸡蛋', pinyin: 'jīdàn', en: 'egg', level: HSKLevel.HSK2 },
  { id: '2-43', char: '件', pinyin: 'jiàn', en: 'measure word for clothes', level: HSKLevel.HSK2 },
  { id: '2-44', char: '教室', pinyin: 'jiàoshì', en: 'classroom', level: HSKLevel.HSK2 },
  { id: '2-45', char: '姐姐', pinyin: 'jiějie', en: 'older sister', level: HSKLevel.HSK2 },
  { id: '2-46', char: '介绍', pinyin: 'jièshào', en: 'to introduce', level: HSKLevel.HSK2 },
  { id: '2-47', char: '进', pinyin: 'jìn', en: 'to enter', level: HSKLevel.HSK2 },
  { id: '2-48', char: '近', pinyin: 'jìn', en: 'near', level: HSKLevel.HSK2 },
  { id: '2-49', char: '就', pinyin: 'jiù', en: 'just; exactly', level: HSKLevel.HSK2 },
  { id: '2-50', char: '觉得', pinyin: 'juéde', en: 'to feel; to think', level: HSKLevel.HSK2 },
  { id: '2-51', char: '咖啡', pinyin: 'kāfēi', en: 'coffee', level: HSKLevel.HSK2 },
  { id: '2-52', char: '开始', pinyin: 'kāishǐ', en: 'to start', level: HSKLevel.HSK2 },
  { id: '2-53', char: '考试', pinyin: 'kǎoshì', en: 'exam', level: HSKLevel.HSK2 },
  { id: '2-54', char: '可能', pinyin: 'kěnéng', en: 'maybe', level: HSKLevel.HSK2 },
  { id: '2-55', char: '可以', pinyin: 'kěyǐ', en: 'can; may', level: HSKLevel.HSK2 },
  { id: '2-56', char: '课', pinyin: 'kè', en: 'lesson', level: HSKLevel.HSK2 },
  { id: '2-57', char: '快', pinyin: 'kuài', en: 'fast', level: HSKLevel.HSK2 },
  { id: '2-58', char: '快乐', pinyin: 'kuàilè', en: 'happy', level: HSKLevel.HSK2 },
  { id: '2-59', char: '累', pinyin: 'lèi', en: 'tired', level: HSKLevel.HSK2 },
  { id: '2-60', char: '离', pinyin: 'lí', en: 'away from', level: HSKLevel.HSK2 },
  { id: '2-61', char: '两', pinyin: 'liǎng', en: 'two', level: HSKLevel.HSK2 },
  { id: '2-62', char: '路', pinyin: 'lù', en: 'road', level: HSKLevel.HSK2 },
  { id: '2-63', char: '旅游', pinyin: 'lǚyóu', en: 'to travel', level: HSKLevel.HSK2 },
  { id: '2-64', char: '卖', pinyin: 'mài', en: 'to sell', level: HSKLevel.HSK2 },
  { id: '2-65', char: '慢', pinyin: 'màn', en: 'slow', level: HSKLevel.HSK2 },
  { id: '2-66', char: '忙', pinyin: 'máng', en: 'busy', level: HSKLevel.HSK2 },
  { id: '2-67', char: '每', pinyin: 'měi', en: 'every', level: HSKLevel.HSK2 },
  { id: '2-68', char: '妹妹', pinyin: 'mèimei', en: 'younger sister', level: HSKLevel.HSK2 },
  { id: '2-69', char: '门', pinyin: 'mén', en: 'door', level: HSKLevel.HSK2 },
  { id: '2-70', char: '男人', pinyin: 'nánrén', en: 'man', level: HSKLevel.HSK2 },
  { id: '2-71', char: '您', pinyin: 'nín', en: 'you (polite)', level: HSKLevel.HSK2 },
  { id: '2-72', char: '牛奶', pinyin: 'niúnǎi', en: 'milk', level: HSKLevel.HSK2 },
  { id: '2-73', char: '女人', pinyin: 'nǚrén', en: 'woman', level: HSKLevel.HSK2 },
  { id: '2-74', char: '旁边', pinyin: 'pángbiān', en: 'side', level: HSKLevel.HSK2 },
  { id: '2-75', char: '跑步', pinyin: 'pǎobù', en: 'to run', level: HSKLevel.HSK2 },
  { id: '2-76', char: '便宜', pinyin: 'piányi', en: 'cheap', level: HSKLevel.HSK2 },
  { id: '2-77', char: '票', pinyin: 'piào', en: 'ticket', level: HSKLevel.HSK2 },
  { id: '2-78', char: '妻子', pinyin: 'qīzi', en: 'wife', level: HSKLevel.HSK2 },
  { id: '2-79', char: '起床', pinyin: 'qǐchuáng', en: 'to get up', level: HSKLevel.HSK2 },
  { id: '2-80', char: '千', pinyin: 'qiān', en: 'thousand', level: HSKLevel.HSK2 },
  { id: '2-81', char: '铅笔', pinyin: 'qiānbǐ', en: 'pencil', level: HSKLevel.HSK2 },
  { id: '2-82', char: '晴', pinyin: 'qíng', en: 'sunny', level: HSKLevel.HSK2 },
  { id: '2-83', char: '去年', pinyin: 'qùnián', en: 'last year', level: HSKLevel.HSK2 },
  { id: '2-84', char: '让', pinyin: 'ràng', en: 'to let', level: HSKLevel.HSK2 },
  { id: '2-85', char: '日', pinyin: 'rì', en: 'day; sun', level: HSKLevel.HSK2 },
  { id: '2-86', char: '上班', pinyin: 'shàngbān', en: 'to go to work', level: HSKLevel.HSK2 },
  { id: '2-87', char: '身体', pinyin: 'shēntǐ', en: 'body', level: HSKLevel.HSK2 },
  { id: '2-88', char: '生病', pinyin: 'shēngbìng', en: 'to get sick', level: HSKLevel.HSK2 },
  { id: '2-89', char: '生日', pinyin: 'shēngrì', en: 'birthday', level: HSKLevel.HSK2 },
  { id: '2-90', char: '时间', pinyin: 'shíjiān', en: 'time', level: HSKLevel.HSK2 },
  { id: '2-91', char: '事情', pinyin: 'shìqing', en: 'matter; thing', level: HSKLevel.HSK2 },
  { id: '2-92', char: '手表', pinyin: 'shǒubiǎo', en: 'watch', level: HSKLevel.HSK2 },
  { id: '2-93', char: '手机', pinyin: 'shǒujī', en: 'mobile phone', level: HSKLevel.HSK2 },
  { id: '2-94', char: '送', pinyin: 'sòng', en: 'to give as gift', level: HSKLevel.HSK2 },
  { id: '2-95', char: '虽然', pinyin: 'suīrán', en: 'although', level: HSKLevel.HSK2 },
  { id: '2-96', char: '但是', pinyin: 'dànshì', en: 'but', level: HSKLevel.HSK2 },
  { id: '2-97', char: '它', pinyin: 'tā', en: 'it', level: HSKLevel.HSK2 },
  { id: '2-98', char: '踢足球', pinyin: 'tīzúqiú', en: 'play football', level: HSKLevel.HSK2 },
  { id: '2-99', char: '题', pinyin: 'tí', en: 'topic; question', level: HSKLevel.HSK2 },
  { id: '2-100', char: '跳舞', pinyin: 'tiàowǔ', en: 'to dance', level: HSKLevel.HSK2 },
  { id: '2-101', char: '外', pinyin: 'wài', en: 'outside', level: HSKLevel.HSK2 },
  { id: '2-102', char: '完', pinyin: 'wán', en: 'to finish', level: HSKLevel.HSK2 },
  { id: '2-103', char: '玩', pinyin: 'wán', en: 'to play', level: HSKLevel.HSK2 },
  { id: '2-104', char: '晚上', pinyin: 'wǎnshang', en: 'evening', level: HSKLevel.HSK2 },
  { id: '2-105', char: '为什么', pinyin: 'wèishénme', en: 'why', level: HSKLevel.HSK2 },
  { id: '2-106', char: '问', pinyin: 'wèn', en: 'to ask', level: HSKLevel.HSK2 },
  { id: '2-107', char: '问题', pinyin: 'wèntí', en: 'question; problem', level: HSKLevel.HSK2 },
  { id: '2-108', char: '西瓜', pinyin: 'xīguā', en: 'watermelon', level: HSKLevel.HSK2 },
  { id: '2-109', char: '希望', pinyin: 'xīwàng', en: 'to hope', level: HSKLevel.HSK2 },
  { id: '2-110', char: '洗', pinyin: 'xǐ', en: 'to wash', level: HSKLevel.HSK2 },
  { id: '2-111', char: '向', pinyin: 'xiàng', en: 'towards', level: HSKLevel.HSK2 },
  { id: '2-112', char: '小时', pinyin: 'xiǎoshí', en: 'hour', level: HSKLevel.HSK2 },
  { id: '2-113', char: '笑', pinyin: 'xiào', en: 'to laugh', level: HSKLevel.HSK2 },
  { id: '2-114', char: '新', pinyin: 'xīn', en: 'new', level: HSKLevel.HSK2 },
  { id: '2-115', char: '姓', pinyin: 'xìng', en: 'surname', level: HSKLevel.HSK2 },
  { id: '2-116', char: '休息', pinyin: 'xiūxi', en: 'to rest', level: HSKLevel.HSK2 },
  { id: '2-117', char: '雪', pinyin: 'xuě', en: 'snow', level: HSKLevel.HSK2 },
  { id: '2-118', char: '颜色', pinyin: 'yánsè', en: 'color', level: HSKLevel.HSK2 },
  { id: '2-119', char: '眼睛', pinyin: 'yǎnjing', en: 'eye', level: HSKLevel.HSK2 },
  { id: '2-120', char: '羊肉', pinyin: 'yángròu', en: 'mutton', level: HSKLevel.HSK2 },
  { id: '2-121', char: '药', pinyin: 'yào', en: 'medicine', level: HSKLevel.HSK2 },
  { id: '2-122', char: '要', pinyin: 'yào', en: 'to want', level: HSKLevel.HSK2 },
  { id: '2-123', char: '也', pinyin: 'yě', en: 'also', level: HSKLevel.HSK2 },
  { id: '2-124', char: '一下', pinyin: 'yíxià', en: 'a little bit', level: HSKLevel.HSK2 },
  { id: '2-125', char: '一起', pinyin: 'yìqǐ', en: 'together', level: HSKLevel.HSK2 },
  { id: '2-126', char: '已经', pinyin: 'yǐjīng', en: 'already', level: HSKLevel.HSK2 },
  { id: '2-127', char: '意思', pinyin: 'yìsi', en: 'meaning', level: HSKLevel.HSK2 },
  { id: '2-128', char: '因为', pinyin: 'yīnwèi', en: 'because', level: HSKLevel.HSK2 },
  { id: '2-129', char: '所以', pinyin: 'suǒyǐ', en: 'so', level: HSKLevel.HSK2 },
  { id: '2-130', char: '阴', pinyin: 'yīn', en: 'overcast', level: HSKLevel.HSK2 },
  { id: '2-131', char: '游泳', pinyin: 'yóuyǒng', en: 'to swim', level: HSKLevel.HSK2 },
  { id: '2-132', char: '右边', pinyin: 'yòubian', en: 'right side', level: HSKLevel.HSK2 },
  { id: '2-133', char: '鱼', pinyin: 'yú', en: 'fish', level: HSKLevel.HSK2 },
  { id: '2-134', char: '远', pinyin: 'yuǎn', en: 'far', level: HSKLevel.HSK2 },
  { id: '2-135', char: '运动', pinyin: 'yùndòng', en: 'sport', level: HSKLevel.HSK2 },
  { id: '2-136', char: '再', pinyin: 'zài', en: 'again', level: HSKLevel.HSK2 },
  { id: '2-137', char: '早上', pinyin: 'zǎoshang', en: 'morning', level: HSKLevel.HSK2 },
  { id: '2-138', char: '丈夫', pinyin: 'zhàngfu', en: 'husband', level: HSKLevel.HSK2 },
  { id: '2-139', char: '找', pinyin: 'zhǎo', en: 'to look for', level: HSKLevel.HSK2 },
  { id: '2-140', char: '着', pinyin: 'zhe', en: 'aspect particle', level: HSKLevel.HSK2 },
  { id: '2-141', char: '真', pinyin: 'zhēn', en: 'really', level: HSKLevel.HSK2 },
  { id: '2-142', char: '正在', pinyin: 'zhèngzài', en: 'in process of', level: HSKLevel.HSK2 },
  { id: '2-143', char: '知道', pinyin: 'zhīdào', en: 'to know', level: HSKLevel.HSK2 },
  { id: '2-144', char: '准备', pinyin: 'zhǔnbèi', en: 'to prepare', level: HSKLevel.HSK2 },
  { id: '2-145', char: '自行车', pinyin: 'zìxíngchē', en: 'bicycle', level: HSKLevel.HSK2 },
  { id: '2-146', char: '走', pinyin: 'zǒu', en: 'to walk', level: HSKLevel.HSK2 },
  { id: '2-147', char: '最', pinyin: 'zuì', en: 'most', level: HSKLevel.HSK2 },
  { id: '2-148', char: '左边', pinyin: 'zuǒbian', en: 'left side', level: HSKLevel.HSK2 },
  { id: '2-149', char: '每', pinyin: 'měi', en: 'every', level: HSKLevel.HSK2 },
  { id: '2-150', char: '门', pinyin: 'mén', en: 'door', level: HSKLevel.HSK2 },

  // --- HSK 3 (300 Words) ---
  { id: '3-1', char: '阿姨', pinyin: 'āyí', en: 'aunt', level: HSKLevel.HSK3 },
  { id: '3-2', char: '啊', pinyin: 'a', en: 'particle indicating surprise', level: HSKLevel.HSK3 },
  { id: '3-3', char: '矮', pinyin: 'ǎi', en: 'short (height)', level: HSKLevel.HSK3 },
  { id: '3-4', char: '爱好', pinyin: 'àihào', en: 'hobby', level: HSKLevel.HSK3 },
  { id: '3-5', char: '安静', pinyin: 'ānjìng', en: 'quiet', level: HSKLevel.HSK3 },
  { id: '3-6', char: '把', pinyin: 'bǎ', en: 'grammar particle', level: HSKLevel.HSK3 },
  { id: '3-7', char: '搬', pinyin: 'bān', en: 'to move (objects)', level: HSKLevel.HSK3 },
  { id: '3-8', char: '班', pinyin: 'bān', en: 'class', level: HSKLevel.HSK3 },
  { id: '3-9', char: '办法', pinyin: 'bànfǎ', en: 'method', level: HSKLevel.HSK3 },
  { id: '3-10', char: '办公室', pinyin: 'bàngōngshì', en: 'office', level: HSKLevel.HSK3 },
  { id: '3-11', char: '半', pinyin: 'bàn', en: 'half', level: HSKLevel.HSK3 },
  { id: '3-12', char: '帮忙', pinyin: 'bāngmáng', en: 'to help', level: HSKLevel.HSK3 },
  { id: '3-13', char: '包', pinyin: 'bāo', en: 'bag', level: HSKLevel.HSK3 },
  { id: '3-14', char: '饱', pinyin: 'bǎo', en: 'full (from eating)', level: HSKLevel.HSK3 },
  { id: '3-15', char: '北方', pinyin: 'běifāng', en: 'North', level: HSKLevel.HSK3 },
  { id: '3-16', char: '被', pinyin: 'bèi', en: 'by (passive)', level: HSKLevel.HSK3 },
  { id: '3-17', char: '鼻子', pinyin: 'bízi', en: 'nose', level: HSKLevel.HSK3 },
  { id: '3-18', char: '比较', pinyin: 'bǐjiào', en: 'relatively', level: HSKLevel.HSK3 },
  { id: '3-19', char: '比赛', pinyin: 'bǐsài', en: 'competition', level: HSKLevel.HSK3 },
  { id: '3-20', char: '必须', pinyin: 'bìxū', en: 'must', level: HSKLevel.HSK3 },
  { id: '3-21', char: '变化', pinyin: 'biànhuà', en: 'change', level: HSKLevel.HSK3 },
  { id: '3-22', char: '表示', pinyin: 'biǎoshì', en: 'to express', level: HSKLevel.HSK3 },
  { id: '3-23', char: '表演', pinyin: 'biǎoyǎn', en: 'performance', level: HSKLevel.HSK3 },
  { id: '3-24', char: '别人', pinyin: 'biéren', en: 'other people', level: HSKLevel.HSK3 },
  { id: '3-25', char: '宾馆', pinyin: 'bīnguǎn', en: 'hotel', level: HSKLevel.HSK3 },
  { id: '3-26', char: '冰箱', pinyin: 'bīngxiāng', en: 'refrigerator', level: HSKLevel.HSK3 },
  { id: '3-27', char: '才', pinyin: 'cái', en: 'just now; only', level: HSKLevel.HSK3 },
  { id: '3-28', char: '菜单', pinyin: 'càidān', en: 'menu', level: HSKLevel.HSK3 },
  { id: '3-29', char: '参加', pinyin: 'cānjiā', en: 'to participate', level: HSKLevel.HSK3 },
  { id: '3-30', char: '草', pinyin: 'cǎo', en: 'grass', level: HSKLevel.HSK3 },
  { id: '3-31', char: '层', pinyin: 'céng', en: 'floor; layer', level: HSKLevel.HSK3 },
  { id: '3-32', char: '差', pinyin: 'chà', en: 'bad; short of', level: HSKLevel.HSK3 },
  { id: '3-33', char: '超市', pinyin: 'chāoshì', en: 'supermarket', level: HSKLevel.HSK3 },
  { id: '3-34', char: '衬衫', pinyin: 'chènshān', en: 'shirt', level: HSKLevel.HSK3 },
  { id: '3-35', char: '成绩', pinyin: 'chéngjì', en: 'score; grade', level: HSKLevel.HSK3 },
  { id: '3-36', char: '城市', pinyin: 'chéngshì', en: 'city', level: HSKLevel.HSK3 },
  { id: '3-37', char: '迟到', pinyin: 'chídào', en: 'to be late', level: HSKLevel.HSK3 },
  { id: '3-38', char: '出现', pinyin: 'chūxiàn', en: 'to appear', level: HSKLevel.HSK3 },
  { id: '3-39', char: '厨房', pinyin: 'chúfáng', en: 'kitchen', level: HSKLevel.HSK3 },
  { id: '3-40', char: '除了', pinyin: 'chúle', en: 'except', level: HSKLevel.HSK3 },
  { id: '3-41', char: '春', pinyin: 'chūn', en: 'spring', level: HSKLevel.HSK3 },
  { id: '3-42', char: '词语', pinyin: 'cíyǔ', en: 'word; expression', level: HSKLevel.HSK3 },
  { id: '3-43', char: '聪明', pinyin: 'cōngming', en: 'smart', level: HSKLevel.HSK3 },
  { id: '3-44', char: '打扫', pinyin: 'dǎsǎo', en: 'to clean', level: HSKLevel.HSK3 },
  { id: '3-45', char: '打算', pinyin: 'dǎsuàn', en: 'to plan', level: HSKLevel.HSK3 },
  { id: '3-46', char: '带', pinyin: 'dài', en: 'to bring', level: HSKLevel.HSK3 },
  { id: '3-47', char: '担心', pinyin: 'dānxīn', en: 'to worry', level: HSKLevel.HSK3 },
  { id: '3-48', char: '蛋糕', pinyin: 'dàngāo', en: 'cake', level: HSKLevel.HSK3 },
  { id: '3-49', char: '当然', pinyin: 'dāngrán', en: 'of course', level: HSKLevel.HSK3 },
  { id: '3-50', char: '地', pinyin: 'de', en: 'particle for adverb', level: HSKLevel.HSK3 },
  { id: '3-51', char: '灯', pinyin: 'dēng', en: 'lamp; light', level: HSKLevel.HSK3 },
  { id: '3-52', char: '低', pinyin: 'dī', en: 'low', level: HSKLevel.HSK3 },
  { id: '3-53', char: '地方', pinyin: 'dìfang', en: 'place', level: HSKLevel.HSK3 },
  { id: '3-54', char: '地铁', pinyin: 'dìtiě', en: 'subway', level: HSKLevel.HSK3 },
  { id: '3-55', char: '地图', pinyin: 'dìtú', en: 'map', level: HSKLevel.HSK3 },
  { id: '3-56', char: '电梯', pinyin: 'diàntī', en: 'elevator', level: HSKLevel.HSK3 },
  { id: '3-57', char: '电子邮件', pinyin: 'diànzǐyóujiàn', en: 'email', level: HSKLevel.HSK3 },
  { id: '3-58', char: '东', pinyin: 'dōng', en: 'East', level: HSKLevel.HSK3 },
  { id: '3-59', char: '冬', pinyin: 'dōng', en: 'Winter', level: HSKLevel.HSK3 },
  { id: '3-60', char: '动物', pinyin: 'dòngwù', en: 'animal', level: HSKLevel.HSK3 },
  { id: '3-61', char: '短', pinyin: 'duǎn', en: 'short', level: HSKLevel.HSK3 },
  { id: '3-62', char: '段', pinyin: 'duàn', en: 'section; part', level: HSKLevel.HSK3 },
  { id: '3-63', char: '锻炼', pinyin: 'duànliàn', en: 'to exercise', level: HSKLevel.HSK3 },
  { id: '3-64', char: '多么', pinyin: 'duōme', en: 'how (wonderful etc)', level: HSKLevel.HSK3 },
  { id: '3-65', char: '饿', pinyin: 'è', en: 'hungry', level: HSKLevel.HSK3 },
  { id: '3-66', char: '耳朵', pinyin: 'ěrduo', en: 'ear', level: HSKLevel.HSK3 },
  { id: '3-67', char: '发', pinyin: 'fā', en: 'to send', level: HSKLevel.HSK3 },
  { id: '3-68', char: '发烧', pinyin: 'fāshāo', en: 'fever', level: HSKLevel.HSK3 },
  { id: '3-69', char: '发现', pinyin: 'fāxiàn', en: 'to discover', level: HSKLevel.HSK3 },
  { id: '3-70', char: '方便', pinyin: 'fāngbiàn', en: 'convenient', level: HSKLevel.HSK3 },
  { id: '3-71', char: '放', pinyin: 'fàng', en: 'to put', level: HSKLevel.HSK3 },
  { id: '3-72', char: '放心', pinyin: 'fàngxīn', en: 'to rest assured', level: HSKLevel.HSK3 },
  { id: '3-73', char: '分', pinyin: 'fēn', en: 'minute; point', level: HSKLevel.HSK3 },
  { id: '3-74', char: '附近', pinyin: 'fùjìn', en: 'nearby', level: HSKLevel.HSK3 },
  { id: '3-75', char: '复习', pinyin: 'fùxí', en: 'to review', level: HSKLevel.HSK3 },
  { id: '3-76', char: '干净', pinyin: 'gānjìng', en: 'clean', level: HSKLevel.HSK3 },
  { id: '3-77', char: '感冒', pinyin: 'gǎnmào', en: 'to have a cold', level: HSKLevel.HSK3 },
  { id: '3-78', char: '感兴趣', pinyin: 'gǎn xìngqù', en: 'to be interested in', level: HSKLevel.HSK3 },
  { id: '3-79', char: '刚才', pinyin: 'gāngcái', en: 'just now', level: HSKLevel.HSK3 },
  { id: '3-80', char: '个子', pinyin: 'gèzi', en: 'height', level: HSKLevel.HSK3 },
  { id: '3-81', char: '根据', pinyin: 'gēnjù', en: 'according to', level: HSKLevel.HSK3 },
  { id: '3-82', char: '跟', pinyin: 'gēn', en: 'with', level: HSKLevel.HSK3 },
  { id: '3-83', char: '更', pinyin: 'gèng', en: 'more', level: HSKLevel.HSK3 },
  { id: '3-84', char: '公斤', pinyin: 'gōngjīn', en: 'kilogram', level: HSKLevel.HSK3 },
  { id: '3-85', char: '公园', pinyin: 'gōngyuán', en: 'park', level: HSKLevel.HSK3 },
  { id: '3-86', char: '故事', pinyin: 'gùshi', en: 'story', level: HSKLevel.HSK3 },
  { id: '3-87', char: '刮风', pinyin: 'guāfēng', en: 'wind blowing', level: HSKLevel.HSK3 },
  { id: '3-88', char: '关', pinyin: 'guān', en: 'to close', level: HSKLevel.HSK3 },
  { id: '3-89', char: '关系', pinyin: 'guānxì', en: 'relationship', level: HSKLevel.HSK3 },
  { id: '3-90', char: '关心', pinyin: 'guānxīn', en: 'to care for', level: HSKLevel.HSK3 },
  { id: '3-91', char: '关于', pinyin: 'guānyú', en: 'about', level: HSKLevel.HSK3 },
  { id: '3-92', char: '国家', pinyin: 'guójiā', en: 'country', level: HSKLevel.HSK3 },
  { id: '3-93', char: '过', pinyin: 'guò', en: 'to pass; to celebrate', level: HSKLevel.HSK3 },
  { id: '3-94', char: '过去', pinyin: 'guòqù', en: 'past', level: HSKLevel.HSK3 },
  { id: '3-95', char: '还是', pinyin: 'háishì', en: 'still; or', level: HSKLevel.HSK3 },
  { id: '3-96', char: '害怕', pinyin: 'hàipà', en: 'to be afraid', level: HSKLevel.HSK3 },
  { id: '3-97', char: '黑板', pinyin: 'hēibǎn', en: 'blackboard', level: HSKLevel.HSK3 },
  { id: '3-98', char: '后来', pinyin: 'hòulái', en: 'later', level: HSKLevel.HSK3 },
  { id: '3-99', char: '护照', pinyin: 'hùzhào', en: 'passport', level: HSKLevel.HSK3 },
  { id: '3-100', char: '花', pinyin: 'huā', en: 'flower; to spend', level: HSKLevel.HSK3 },
  { id: '3-101', char: '画', pinyin: 'huà', en: 'to draw', level: HSKLevel.HSK3 },
  { id: '3-102', char: '坏', pinyin: 'huài', en: 'bad; broken', level: HSKLevel.HSK3 },
  { id: '3-103', char: '欢迎', pinyin: 'huānyíng', en: 'to welcome', level: HSKLevel.HSK3 },
  { id: '3-104', char: '环境', pinyin: 'huánjìng', en: 'environment', level: HSKLevel.HSK3 },
  { id: '3-105', char: '换', pinyin: 'huàn', en: 'to change', level: HSKLevel.HSK3 },
  { id: '3-106', char: '黄河', pinyin: 'Huáng Hé', en: 'Yellow River', level: HSKLevel.HSK3 },
  { id: '3-107', char: '回答', pinyin: 'huídá', en: 'to answer', level: HSKLevel.HSK3 },
  { id: '3-108', char: '会议', pinyin: 'huìyì', en: 'meeting', level: HSKLevel.HSK3 },
  { id: '3-109', char: '或者', pinyin: 'huòzhě', en: 'or', level: HSKLevel.HSK3 },
  { id: '3-110', char: '几乎', pinyin: 'jīhū', en: 'almost', level: HSKLevel.HSK3 },
  { id: '3-111', char: '机会', pinyin: 'jīhuì', en: 'opportunity', level: HSKLevel.HSK3 },
  { id: '3-112', char: '极', pinyin: 'jí', en: 'extremely', level: HSKLevel.HSK3 },
  { id: '3-113', char: '记得', pinyin: 'jìde', en: 'to remember', level: HSKLevel.HSK3 },
  { id: '3-114', char: '季节', pinyin: 'jìjié', en: 'season', level: HSKLevel.HSK3 },
  { id: '3-115', char: '检查', pinyin: 'jiǎnchá', en: 'to check', level: HSKLevel.HSK3 },
  { id: '3-116', char: '简单', pinyin: 'jiǎndān', en: 'simple', level: HSKLevel.HSK3 },
  { id: '3-117', char: '见面', pinyin: 'jiànmiàn', en: 'to meet', level: HSKLevel.HSK3 },
  { id: '3-118', char: '健康', pinyin: 'jiànkāng', en: 'healthy', level: HSKLevel.HSK3 },
  { id: '3-119', char: '讲', pinyin: 'jiǎng', en: 'to speak; to explain', level: HSKLevel.HSK3 },
  { id: '3-120', char: '教', pinyin: 'jiāo', en: 'to teach', level: HSKLevel.HSK3 },
  { id: '3-121', char: '角', pinyin: 'jiǎo', en: 'horn; corner', level: HSKLevel.HSK3 },
  { id: '3-122', char: '脚', pinyin: 'jiǎo', en: 'foot', level: HSKLevel.HSK3 },
  { id: '3-123', char: '接', pinyin: 'jiē', en: 'to receive', level: HSKLevel.HSK3 },
  { id: '3-124', char: '街道', pinyin: 'jiēdào', en: 'street', level: HSKLevel.HSK3 },
  { id: '3-125', char: '节目', pinyin: 'jiémù', en: 'program', level: HSKLevel.HSK3 },
  { id: '3-126', char: '节日', pinyin: 'jiérì', en: 'holiday', level: HSKLevel.HSK3 },
  { id: '3-127', char: '结婚', pinyin: 'jiéhūn', en: 'to marry', level: HSKLevel.HSK3 },
  { id: '3-128', char: '结束', pinyin: 'jiéshù', en: 'to end', level: HSKLevel.HSK3 },
  { id: '3-129', char: '解决', pinyin: 'jiějué', en: 'to solve', level: HSKLevel.HSK3 },
  { id: '3-130', char: '借', pinyin: 'jiè', en: 'to borrow', level: HSKLevel.HSK3 },
  { id: '3-131', char: '经常', pinyin: 'jīngcháng', en: 'often', level: HSKLevel.HSK3 },
  { id: '3-132', char: '经过', pinyin: 'jīngguò', en: 'to pass by', level: HSKLevel.HSK3 },
  { id: '3-133', char: '经理', pinyin: 'jīnglǐ', en: 'manager', level: HSKLevel.HSK3 },
  { id: '3-134', char: '久', pinyin: 'jiǔ', en: 'long time', level: HSKLevel.HSK3 },
  { id: '3-135', char: '旧', pinyin: 'jiù', en: 'old', level: HSKLevel.HSK3 },
  { id: '3-136', char: '句子', pinyin: 'jùzi', en: 'sentence', level: HSKLevel.HSK3 },
  { id: '3-137', char: '决定', pinyin: 'juédìng', en: 'to decide', level: HSKLevel.HSK3 },
  { id: '3-138', char: '可爱', pinyin: 'kě\'ài', en: 'cute', level: HSKLevel.HSK3 },
  { id: '3-139', char: '渴', pinyin: 'kě', en: 'thirsty', level: HSKLevel.HSK3 },
  { id: '3-140', char: '刻', pinyin: 'kè', en: 'quarter (hour)', level: HSKLevel.HSK3 },
  { id: '3-141', char: '客人', pinyin: 'kèrén', en: 'guest', level: HSKLevel.HSK3 },
  { id: '3-142', char: '空调', pinyin: 'kōngtiáo', en: 'air conditioner', level: HSKLevel.HSK3 },
  { id: '3-143', char: '口', pinyin: 'kǒu', en: 'mouth', level: HSKLevel.HSK3 },
  { id: '3-144', char: '哭', pinyin: 'kū', en: 'to cry', level: HSKLevel.HSK3 },
  { id: '3-145', char: '裤子', pinyin: 'kùzi', en: 'pants', level: HSKLevel.HSK3 },
  { id: '3-146', char: '筷子', pinyin: 'kuàizi', en: 'chopsticks', level: HSKLevel.HSK3 },
  { id: '3-147', char: '蓝', pinyin: 'lán', en: 'blue', level: HSKLevel.HSK3 },
  { id: '3-148', char: '老', pinyin: 'lǎo', en: 'old', level: HSKLevel.HSK3 },
  { id: '3-149', char: '离开', pinyin: 'líkāi', en: 'to leave', level: HSKLevel.HSK3 },
  { id: '3-150', char: '礼物', pinyin: 'lǐwù', en: 'gift', level: HSKLevel.HSK3 },
  { id: '3-151', char: '历史', pinyin: 'lìshǐ', en: 'history', level: HSKLevel.HSK3 },
  { id: '3-152', char: '脸', pinyin: 'liǎn', en: 'face', level: HSKLevel.HSK3 },
  { id: '3-153', char: '练习', pinyin: 'liànxí', en: 'to practice', level: HSKLevel.HSK3 },
  { id: '3-154', char: '辆', pinyin: 'liàng', en: 'measure word for vehicles', level: HSKLevel.HSK3 },
  { id: '3-155', char: '聊天', pinyin: 'liáotiān', en: 'to chat', level: HSKLevel.HSK3 },
  { id: '3-156', char: '了解', pinyin: 'liǎojiě', en: 'to understand', level: HSKLevel.HSK3 },
  { id: '3-157', char: '邻居', pinyin: 'línjū', en: 'neighbor', level: HSKLevel.HSK3 },
  { id: '3-158', char: '留学', pinyin: 'liúxué', en: 'study abroad', level: HSKLevel.HSK3 },
  { id: '3-159', char: '楼', pinyin: 'lóu', en: 'building; floor', level: HSKLevel.HSK3 },
  { id: '3-160', char: '绿', pinyin: 'lǜ', en: 'green', level: HSKLevel.HSK3 },
  { id: '3-161', char: '马', pinyin: 'mǎ', en: 'horse', level: HSKLevel.HSK3 },
  { id: '3-162', char: '马上', pinyin: 'mǎshàng', en: 'immediately', level: HSKLevel.HSK3 },
  { id: '3-163', char: '满意', pinyin: 'mǎnyì', en: 'satisfied', level: HSKLevel.HSK3 },
  { id: '3-164', char: '帽子', pinyin: 'màozi', en: 'hat', level: HSKLevel.HSK3 },
  { id: '3-165', char: '米', pinyin: 'mǐ', en: 'meter', level: HSKLevel.HSK3 },
  { id: '3-166', char: '面包', pinyin: 'miànbāo', en: 'bread', level: HSKLevel.HSK3 },
  { id: '3-167', char: '面条', pinyin: 'miàntiáo', en: 'noodles', level: HSKLevel.HSK3 },
  { id: '3-168', char: '明白', pinyin: 'míngbai', en: 'to understand', level: HSKLevel.HSK3 },
  { id: '3-169', char: '拿', pinyin: 'ná', en: 'to hold; to take', level: HSKLevel.HSK3 },
  { id: '3-170', char: '奶奶', pinyin: 'nǎinai', en: 'grandmother', level: HSKLevel.HSK3 },
  { id: '3-171', char: '南', pinyin: 'nán', en: 'South', level: HSKLevel.HSK3 },
  { id: '3-172', char: '难', pinyin: 'nán', en: 'difficult', level: HSKLevel.HSK3 },
  { id: '3-173', char: '难过', pinyin: 'nánguò', en: 'sad', level: HSKLevel.HSK3 },
  { id: '3-174', char: '年级', pinyin: 'niánjí', en: 'grade', level: HSKLevel.HSK3 },
  { id: '3-175', char: '年轻', pinyin: 'niánqīng', en: 'young', level: HSKLevel.HSK3 },
  { id: '3-176', char: '鸟', pinyin: 'niǎo', en: 'bird', level: HSKLevel.HSK3 },
  { id: '3-177', char: '努力', pinyin: 'nǔlì', en: 'hardworking', level: HSKLevel.HSK3 },
  { id: '3-178', char: '爬山', pinyin: 'páshān', en: 'to climb a mountain', level: HSKLevel.HSK3 },
  { id: '3-179', char: '盘子', pinyin: 'pánzi', en: 'plate', level: HSKLevel.HSK3 },
  { id: '3-180', char: '胖', pinyin: 'pàng', en: 'fat', level: HSKLevel.HSK3 },
  { id: '3-181', char: '皮鞋', pinyin: 'píxié', en: 'leather shoes', level: HSKLevel.HSK3 },
  { id: '3-182', char: '啤酒', pinyin: 'píjiǔ', en: 'beer', level: HSKLevel.HSK3 },
  { id: '3-183', char: '普通话', pinyin: 'pǔtōnghuà', en: 'Mandarin', level: HSKLevel.HSK3 },
  { id: '3-184', char: '其实', pinyin: 'qíshí', en: 'actually', level: HSKLevel.HSK3 },
  { id: '3-185', char: '其他', pinyin: 'qítā', en: 'other', level: HSKLevel.HSK3 },
  { id: '3-186', char: '奇怪', pinyin: 'qíguài', en: 'strange', level: HSKLevel.HSK3 },
  { id: '3-187', char: '骑', pinyin: 'qí', en: 'to ride', level: HSKLevel.HSK3 },
  { id: '3-188', char: '起飞', pinyin: 'qǐfēi', en: 'to take off', level: HSKLevel.HSK3 },
  { id: '3-189', char: '清楚', pinyin: 'qīngchu', en: 'clear', level: HSKLevel.HSK3 },
  { id: '3-190', char: '秋', pinyin: 'qiū', en: 'Autumn', level: HSKLevel.HSK3 },
  { id: '3-191', char: '裙子', pinyin: 'qúnzi', en: 'skirt', level: HSKLevel.HSK3 },
  { id: '3-192', char: '然后', pinyin: 'ránhòu', en: 'then', level: HSKLevel.HSK3 },
  { id: '3-193', char: '热情', pinyin: 'rèqíng', en: 'enthusiastic', level: HSKLevel.HSK3 },
  { id: '3-194', char: '认为', pinyin: 'rènwéi', en: 'to think', level: HSKLevel.HSK3 },
  { id: '3-195', char: '认真', pinyin: 'rènzhēn', en: 'serious', level: HSKLevel.HSK3 },
  { id: '3-196', char: '容易', pinyin: 'róngyì', en: 'easy', level: HSKLevel.HSK3 },
  { id: '3-197', char: '如果', pinyin: 'rúguǒ', en: 'if', level: HSKLevel.HSK3 },
  { id: '3-198', char: '伞', pinyin: 'sǎn', en: 'umbrella', level: HSKLevel.HSK3 },
  { id: '3-199', char: '上网', pinyin: 'shàngwǎng', en: 'to surf the internet', level: HSKLevel.HSK3 },
  { id: '3-200', char: '生气', pinyin: 'shēngqì', en: 'angry', level: HSKLevel.HSK3 },
  { id: '3-201', char: '声音', pinyin: 'shēngyīn', en: 'sound; voice', level: HSKLevel.HSK3 },
  { id: '3-202', char: '世界', pinyin: 'shìjiè', en: 'world', level: HSKLevel.HSK3 },
  { id: '3-203', char: '试', pinyin: 'shì', en: 'to try', level: HSKLevel.HSK3 },
  { id: '3-204', char: '瘦', pinyin: 'shòu', en: 'thin', level: HSKLevel.HSK3 },
  { id: '3-205', char: '叔叔', pinyin: 'shūshu', en: 'uncle', level: HSKLevel.HSK3 },
  { id: '3-206', char: '舒服', pinyin: 'shūfu', en: 'comfortable', level: HSKLevel.HSK3 },
  { id: '3-207', char: '树', pinyin: 'shù', en: 'tree', level: HSKLevel.HSK3 },
  { id: '3-208', char: '数学', pinyin: 'shùxué', en: 'math', level: HSKLevel.HSK3 },
  { id: '3-209', char: '刷牙', pinyin: 'shuāyá', en: 'to brush teeth', level: HSKLevel.HSK3 },
  { id: '3-210', char: '双', pinyin: 'shuāng', en: 'pair', level: HSKLevel.HSK3 },
  { id: '3-211', char: '水平', pinyin: 'shuǐpíng', en: 'level', level: HSKLevel.HSK3 },
  { id: '3-212', char: '司机', pinyin: 'sījī', en: 'driver', level: HSKLevel.HSK3 },
  { id: '3-213', char: '太阳', pinyin: 'tàiyáng', en: 'sun', level: HSKLevel.HSK3 },
  { id: '3-214', char: '特别', pinyin: 'tèbié', en: 'special', level: HSKLevel.HSK3 },
  { id: '3-215', char: '疼', pinyin: 'téng', en: 'pain', level: HSKLevel.HSK3 },
  { id: '3-216', char: '提高', pinyin: 'tígāo', en: 'to improve', level: HSKLevel.HSK3 },
  { id: '3-217', char: '体育', pinyin: 'tǐyù', en: 'PE; sports', level: HSKLevel.HSK3 },
  { id: '3-218', char: '甜', pinyin: 'tián', en: 'sweet', level: HSKLevel.HSK3 },
  { id: '3-219', char: '条', pinyin: 'tiáo', en: 'measure word for long objects', level: HSKLevel.HSK3 },
  { id: '3-220', char: '同事', pinyin: 'tóngshì', en: 'colleague', level: HSKLevel.HSK3 },
  { id: '3-221', char: '同意', pinyin: 'tóngyì', en: 'to agree', level: HSKLevel.HSK3 },
  { id: '3-222', char: '头发', pinyin: 'tóufa', en: 'hair', level: HSKLevel.HSK3 },
  { id: '3-223', char: '突然', pinyin: 'tūrán', en: 'suddenly', level: HSKLevel.HSK3 },
  { id: '3-224', char: '图书馆', pinyin: 'túshūguǎn', en: 'library', level: HSKLevel.HSK3 },
  { id: '3-225', char: '腿', pinyin: 'tuǐ', en: 'leg', level: HSKLevel.HSK3 },
  { id: '3-226', char: '完成', pinyin: 'wánchéng', en: 'to complete', level: HSKLevel.HSK3 },
  { id: '3-227', char: '碗', pinyin: 'wǎn', en: 'bowl', level: HSKLevel.HSK3 },
  { id: '3-228', char: '万', pinyin: 'wàn', en: 'ten thousand', level: HSKLevel.HSK3 },
  { id: '3-229', char: '忘记', pinyin: 'wàngjì', en: 'to forget', level: HSKLevel.HSK3 },
  { id: '3-230', char: '为', pinyin: 'wèi', en: 'for', level: HSKLevel.HSK3 },
  { id: '3-231', char: '为了', pinyin: 'wèile', en: 'in order to', level: HSKLevel.HSK3 },
  { id: '3-232', char: '位', pinyin: 'wèi', en: 'polite measure word for people', level: HSKLevel.HSK3 },
  { id: '3-233', char: '文化', pinyin: 'wénhuà', en: 'culture', level: HSKLevel.HSK3 },
  { id: '3-234', char: '西', pinyin: 'xī', en: 'West', level: HSKLevel.HSK3 },
  { id: '3-235', char: '习惯', pinyin: 'xíguàn', en: 'habit', level: HSKLevel.HSK3 },
  { id: '3-236', char: '洗手间', pinyin: 'xǐshǒujiān', en: 'toilet', level: HSKLevel.HSK3 },
  { id: '3-237', char: '洗澡', pinyin: 'xǐzǎo', en: 'to take a shower', level: HSKLevel.HSK3 },
  { id: '3-238', char: '夏', pinyin: 'xià', en: 'Summer', level: HSKLevel.HSK3 },
  { id: '3-239', char: '先', pinyin: 'xiān', en: 'first', level: HSKLevel.HSK3 },
  { id: '3-240', char: '相信', pinyin: 'xiāngxìn', en: 'to believe', level: HSKLevel.HSK3 },
  { id: '3-241', char: '香蕉', pinyin: 'xiāngjiāo', en: 'banana', level: HSKLevel.HSK3 },
  { id: '3-242', char: '像', pinyin: 'xiàng', en: 'to resemble', level: HSKLevel.HSK3 },
  { id: '3-243', char: '小心', pinyin: 'xiǎoxīn', en: 'careful', level: HSKLevel.HSK3 },
  { id: '3-244', char: '校长', pinyin: 'xiàozhǎng', en: 'principal', level: HSKLevel.HSK3 },
  { id: '3-245', char: '新闻', pinyin: 'xīnwén', en: 'news', level: HSKLevel.HSK3 },
  { id: '3-246', char: '新鲜', pinyin: 'xīnxiān', en: 'fresh', level: HSKLevel.HSK3 },
  { id: '3-247', char: '信用卡', pinyin: 'xìnyòngkǎ', en: 'credit card', level: HSKLevel.HSK3 },
  { id: '3-248', char: '行李箱', pinyin: 'xínglixiāng', en: 'suitcase', level: HSKLevel.HSK3 },
  { id: '3-249', char: '熊猫', pinyin: 'xióngmāo', en: 'panda', level: HSKLevel.HSK3 },
  { id: '3-250', char: '需要', pinyin: 'xūyào', en: 'to need', level: HSKLevel.HSK3 },
  { id: '3-251', char: '选择', pinyin: 'xuǎnzé', en: 'to choose', level: HSKLevel.HSK3 },
  { id: '3-252', char: '要求', pinyin: 'yāoqiú', en: 'requirement', level: HSKLevel.HSK3 },
  { id: '3-253', char: '爷爷', pinyin: 'yéye', en: 'grandfather', level: HSKLevel.HSK3 },
  { id: '3-254', char: '一定', pinyin: 'yídìng', en: 'must; certainly', level: HSKLevel.HSK3 },
  { id: '3-255', char: '一共', pinyin: 'yígòng', en: 'altogether', level: HSKLevel.HSK3 },
  { id: '3-256', char: '一会儿', pinyin: 'yíhuìr', en: 'a while', level: HSKLevel.HSK3 },
  { id: '3-257', char: '一样', pinyin: 'yíyàng', en: 'same', level: HSKLevel.HSK3 },
  { id: '3-258', char: '一般', pinyin: 'yìbān', en: 'ordinary', level: HSKLevel.HSK3 },
  { id: '3-259', char: '一边', pinyin: 'yìbiān', en: 'one side', level: HSKLevel.HSK3 },
  { id: '3-260', char: '一直', pinyin: 'yìzhí', en: 'straight; continuously', level: HSKLevel.HSK3 },
  { id: '3-261', char: '以前', pinyin: 'yǐqián', en: 'before', level: HSKLevel.HSK3 },
  { id: '3-262', char: '音乐', pinyin: 'yīnyuè', en: 'music', level: HSKLevel.HSK3 },
  { id: '3-263', char: '银行', pinyin: 'yínháng', en: 'bank', level: HSKLevel.HSK3 },
  { id: '3-264', char: '饮料', pinyin: 'yǐnliào', en: 'beverage', level: HSKLevel.HSK3 },
  { id: '3-265', char: '应该', pinyin: 'yīnggāi', en: 'should', level: HSKLevel.HSK3 },
  { id: '3-266', char: '影响', pinyin: 'yǐngxiǎng', en: 'influence', level: HSKLevel.HSK3 },
  { id: '3-267', char: '用', pinyin: 'yòng', en: 'to use', level: HSKLevel.HSK3 },
  { id: '3-268', char: '游戏', pinyin: 'yóuxì', en: 'game', level: HSKLevel.HSK3 },
  { id: '3-269', char: '有名', pinyin: 'yǒumíng', en: 'famous', level: HSKLevel.HSK3 },
  { id: '3-270', char: '又', pinyin: 'yòu', en: 'again', level: HSKLevel.HSK3 },
  { id: '3-271', char: '遇到', pinyin: 'yùdào', en: 'to encounter', level: HSKLevel.HSK3 },
  { id: '3-272', char: '元', pinyin: 'yuán', en: 'currency unit', level: HSKLevel.HSK3 },
  { id: '3-273', char: '愿意', pinyin: 'yuànyì', en: 'willing', level: HSKLevel.HSK3 },
  { id: '3-274', char: '月亮', pinyin: 'yuèliang', en: 'moon', level: HSKLevel.HSK3 },
  { id: '3-275', char: '越', pinyin: 'yuè', en: 'the more...', level: HSKLevel.HSK3 },
  { id: '3-276', char: '站', pinyin: 'zhàn', en: 'station; to stand', level: HSKLevel.HSK3 },
  { id: '3-277', char: '张', pinyin: 'zhāng', en: 'measure word for flat objects', level: HSKLevel.HSK3 },
  { id: '3-278', char: '照顾', pinyin: 'zhàogù', en: 'to take care of', level: HSKLevel.HSK3 },
  { id: '3-279', char: '照片', pinyin: 'zhàopiàn', en: 'photo', level: HSKLevel.HSK3 },
  { id: '3-280', char: '照相机', pinyin: 'zhàoxiàngjī', en: 'camera', level: HSKLevel.HSK3 },
  { id: '3-281', char: '只', pinyin: 'zhǐ', en: 'only', level: HSKLevel.HSK3 },
  { id: '3-282', char: '只', pinyin: 'zhī', en: 'measure word for animals', level: HSKLevel.HSK3 },
  { id: '3-283', char: '中间', pinyin: 'zhōngjiān', en: 'middle', level: HSKLevel.HSK3 },
  { id: '3-284', char: '中文', pinyin: 'Zhōngwén', en: 'Chinese language', level: HSKLevel.HSK3 },
  { id: '3-285', char: '终于', pinyin: 'zhōngyú', en: 'finally', level: HSKLevel.HSK3 },
  { id: '3-286', char: '种', pinyin: 'zhǒng', en: 'kind; type', level: HSKLevel.HSK3 },
  { id: '3-287', char: '重要', pinyin: 'zhòngyào', en: 'important', level: HSKLevel.HSK3 },
  { id: '3-288', char: '周末', pinyin: 'zhōumò', en: 'weekend', level: HSKLevel.HSK3 },
  { id: '3-289', char: '主要', pinyin: 'zhǔyào', en: 'main', level: HSKLevel.HSK3 },
  { id: '3-290', char: '注意', pinyin: 'zhùyì', en: 'to pay attention', level: HSKLevel.HSK3 },
  { id: '3-291', char: '着急', pinyin: 'zháojí', en: 'worried', level: HSKLevel.HSK3 },
  { id: '3-292', char: '自己', pinyin: 'zìjǐ', en: 'oneself', level: HSKLevel.HSK3 },
  { id: '3-293', char: '总是', pinyin: 'zǒngshì', en: 'always', level: HSKLevel.HSK3 },
  { id: '3-294', char: '嘴', pinyin: 'zuǐ', en: 'mouth', level: HSKLevel.HSK3 },
  { id: '3-295', char: '最近', pinyin: 'zuìjìn', en: 'recently', level: HSKLevel.HSK3 },
  { id: '3-296', char: '作业', pinyin: 'zuòyè', en: 'homework', level: HSKLevel.HSK3 },
  { id: '3-297', char: '作用', pinyin: 'zuòyòng', en: 'effect', level: HSKLevel.HSK3 },
  { id: '3-298', char: '做', pinyin: 'zuò', en: 'to do', level: HSKLevel.HSK3 },
  { id: '3-299', char: '坐', pinyin: 'zuò', en: 'to sit', level: HSKLevel.HSK3 },
  { id: '3-300', char: '座', pinyin: 'zuò', en: 'measure word for buildings', level: HSKLevel.HSK3 },
];

export const GRAMMAR_TOPICS: GrammarTopic[] = [
  // HSK 1
  { id: 'g1-1', title: 'The "Shi... De" Construction', level: HSKLevel.HSK1, description: 'Emphasizing details of past events.' },
  { id: 'g1-2', title: 'Basic Sentence Order', level: HSKLevel.HSK1, description: 'Subject + Verb + Object structure.' },
  { id: 'g1-3', title: 'Yes/No Questions with "Ma"', level: HSKLevel.HSK1, description: 'How to form basic questions.' },
  { id: 'g1-4', title: 'Possessive Particle "De"', level: HSKLevel.HSK1, description: 'Indicating possession or relationship.' },
  
  // HSK 2
  { id: 'g2-1', title: 'The "Ba" Structure', level: HSKLevel.HSK2, description: 'Using 把 to manipulate objects.' },
  { id: 'g2-2', title: 'Comparisons with "Bi"', level: HSKLevel.HSK2, description: 'Expressing "A is more than B".' },
  { id: 'g2-3', title: 'Result Complements', level: HSKLevel.HSK2, description: 'Verbs followed by the result of the action.' },

  // HSK 3
  { id: 'g3-1', title: 'Passive Voice with "Bei"', level: HSKLevel.HSK3, description: 'How to say something was done by someone.' },
  { id: 'g3-2', title: 'The Particle "Le"', level: HSKLevel.HSK3, description: 'Change of state or completed action.' },
  { id: 'g3-3', title: 'Complements of Direction', level: HSKLevel.HSK3, description: 'Indicating direction of movement.' },
];
